# Generated by release-cli.yml (ADR-0050) — do not edit by hand.
class Skl < Formula
  desc "Self-hosted, cross-harness skill distribution & management CLI"
  homepage "https://useskl.com"
  version "0.3.0"

  on_macos do
    on_arm do
      url "https://github.com/loopdoop/skl/releases/download/v0.3.0/skl-darwin-arm64"
      sha256 "f9c0885aad5a5de2d2fe6b46ff17b05f3d3d5e955dc4222fbf97aba7303d237d"
    end
    on_intel do
      url "https://github.com/loopdoop/skl/releases/download/v0.3.0/skl-darwin-x64"
      sha256 "1db34a0865a8268ed46f264b4b6c2ba3fcd91bb421e4e6c711331bccb3f4fa36"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/loopdoop/skl/releases/download/v0.3.0/skl-linux-arm64"
      sha256 "e00ee3daab6b4f8d0542d8076899b8372fd6743fb362f34bca643e3a7dcf7c29"
    end
    on_intel do
      url "https://github.com/loopdoop/skl/releases/download/v0.3.0/skl-linux-x64"
      sha256 "57c66b28b6cd8f80bc71b6605d66495614f2cbf7dfacb83ce3f105ff6d360bf8"
    end
  end

  def install
    bin.install Dir["skl-*"].first => "skl"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/skl --version")
  end
end
