# Generated by release-cli.yml (ADR-0050) — do not edit by hand.
class Skl < Formula
  desc "Self-hosted, cross-harness skill distribution & management CLI"
  homepage "https://useskl.com"
  version "0.2.2"

  on_macos do
    on_arm do
      url "https://github.com/loopdoop/skl/releases/download/v0.2.2/skl-darwin-arm64"
      sha256 "11f4b2c81fcb654583d352719eaa1ca882912e94f1e5d131c41996781ff70d2b"
    end
    on_intel do
      url "https://github.com/loopdoop/skl/releases/download/v0.2.2/skl-darwin-x64"
      sha256 "173843497cb53d0955e4d2b40618683d508038d88c75887cd0cc5e0435010e74"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/loopdoop/skl/releases/download/v0.2.2/skl-linux-arm64"
      sha256 "e0c5370b0d19b283d682427148c34d160bea9caa9a7315476619926ac2b8129f"
    end
    on_intel do
      url "https://github.com/loopdoop/skl/releases/download/v0.2.2/skl-linux-x64"
      sha256 "ec7a3fd4e319f0cb2067a086f252913af325a70262e7841945b9f00042571225"
    end
  end

  def install
    bin.install Dir["skl-*"].first => "skl"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/skl --version")
  end
end
